
# This file was *autogenerated* from the file kl.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p143 = RealNumber('1.143'); _sage_const_1 = Integer(1); _sage_const_5p120 = RealNumber('5.120')#!/usr/bin/sage -python

# Spurs

l1 = _sage_const_1p143 

# Jazz

l2 = _sage_const_5p120 

# Implied probabilities

i1 = _sage_const_1 /l1
i2 = _sage_const_1 /l2

# Equal-information gain odds ratio estimate for Spurs

o = (i2**i2*(_sage_const_1 -i2)**(_sage_const_1 -i2)/(i1**i1*(_sage_const_1 -i1)**(_sage_const_1 -i1)))**(_sage_const_1 /(i1+i2-_sage_const_1 ))

# Spurs KL estimate

p1 = _sage_const_1 /(o+_sage_const_1 )

# Jazz KL estimate

p2 = o/(o+_sage_const_1 )

print("Spurs implied Pr=%s" % i1)
print("Spurs estimated Pr=%s" % p1)

print("Jazz implied Pr=%s" % i2)
print("Jazz estimated Pr=%s" % p2)

